// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://hjcbyqvtllvonvrrlnrd.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqY2J5cXZ0bGx2b252cnJsbnJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA3ODAwMjQsImV4cCI6MjA0NjM1NjAyNH0.iLnsKif6--jX2CkAnuxES1R-Q5hIovaTamnqxHTPJEY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);